### ISSUE TITLE
games-roguelike/cataclysm-dda-0.9e_p3 fails to build

### ISSUE THREAD

**Issue by 2xsaiko** [leycec/raiagent#102]
[Build info/log](https://gist.github.com/2xsaiko/bf0e36cd9d52ec7dc4dd470d57bc03c4)

Originally I tried to update the package to 0.F but that gave me a different error.

**Comment by leycec** [comment]
*ohnoes*

On the bright side of the post-post-apocalypse, I didn't even know 0.F was already out! So, that's great. I'll try bumping to 0.F on my side and see if I can't get this worky.

Zombie Gentooer thanks you for the rotting heads up. :zombie:

**Comment by leycec** [comment]
This error in your helpful logfile is deeply suspicious:

```
At global scope:
[01m[Kcc1plus:[m[K [01;36m[Knote: [m[Kunrecognized command-line option ‘[01m[K-Wno-unknown-warning-option[m[K’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
```

The `-Wno-unknown-warning-option` option is *only* supported by Clang. GCC doesn't support that option, so Cataclysm's GCC-specific `Makefile` shouldn't be passing that option to GCC. That said... I must confess I've never seen this myself. Cataclysm 0.E-3 built perfectly for me, so that's a bit of a rotting head-scratcher.

Let's just bump to 0.F and pretend this never happened. Male Zombie Gentooer is sad! :zombie_man:

**Comment by 2xsaiko** [comment]
Looks to me like it gets unconditionally enabled here: [Makefile:107](https://github.com/CleverRaven/Cataclysm-DDA/blob/0.E-3/Makefile#L107). And it's still there in 0.F. Makes it even stranger why it compiled for you but not for me if it's not a valid GCC option... Maybe different behavior for different GCC versions?

**Comment by leycec** [comment]
If I had a moustache, I would be perplexedly rubbing it. Thanks a heap for tracking that down, though! I'll patch that away in our ebuild. It *might* not actually be a real issue, but it's obfuscating underlying real issues.

Also, I face-planted into the same compilation issue with 0.F you probably hit. The ncurses-based CLI interface builds fine, but the SDL-based GUI interface almost immediately fails with this dodgy complaint:

```
cc1plus: error: pch/main-pch.hpp.gch: not used
because `_XOPEN_SOURCE' not defined
[-Werror=invalid-pch]
```

That's... horrible. Their `Makefile` is clearly broken. Let's see if we can just patch that away like always. And this is why Cataclysm still isn't in Portage, folks. `</sigh>`

**Comment by leycec** [comment]
**Ah-ha.** We are now hitting a [known Cataclysm build issue](https://github.com/CleverRaven/Cataclysm-DDA/issues/42598), whose resolution thankfully appears trivial: just run `emake clean` in between compiling the ncurses and SDL interfaces.

We got this. :wink:

**Comment by 2xsaiko** [comment]
Yup, that's exactly the one I was hitting. That does make it sound like their build setup is broken indeed, even more so than having both a Makefile and CMakeLists that have to be separately maintained. Fun! \o/

**Comment by leycec** [comment]
Well, *that* took dramatically longer than expected. Everything has been bumped to 0.9F (Frank) and actually appears to now work – but don't take my shrill word for it! Check it out and let me know if all's well that ends well; if not, feel free to reopen this. <sup>*...please don't*</sup>

In related news, **this was complete and utter Hell.** I don't play C:DDA much anymore and don't necessarily have the spare time to continue maintaining C:DDA ebuilds in perpetuity, especially because upstream **(A)** doesn't adequately test their makefiles, 
**(B)** can't be bothered to fix issues in their makefiles, and **(C)** insanely maintains two completely different build systems in parallel.

Because of these issues and because the non-cmake makefiles are becoming Hell Incarnate to support, I'm probably going to do the following on the next bump:

1. Refactor everything to use cmake instead.
2. Submit the resulting ebuild to Portage itself as a PR. There's an [open Gentoo Bugzilla issue requesting exactly this](https://bugs.gentoo.org/show_bug.cgi?id=699288), so we'll be able to hit two plague-infested birds with one stone.
3. Remove C:DDA from this overlay once accepted.

Until then, we trudge dolefully on. `</sigh>`

**Comment by 2xsaiko** [comment]
Thanks a lot, it's working now! And yeah, I think getting it to use cmake and then submitting to the main gentoo repository is a good idea, I should probably do that with some of my ebuilds as well because I have a lot of them at this point that I also can't maintain all by myself. An RSS reader that I only added the feeds for some of the packages in and look at once in a while only does so much, haha
