### ISSUE TITLE
games-roguelike/cataclysm-dda: Build fails with USE=-nls

### ISSUE THREAD

**Issue by atlaua** [leycec/raiagent#51]
If USE=-nls is set, the build fails after linking the executable with the error message `make: *** No rule to make target 'en', needed by 'all'.  Stop.`

Build log: See issue #49

**Comment by leycec** [comment]
**Fixed by 31a0d0c4b.**

This was actually fairly non-trivial to debug and, ultimately, solve. Why? Because this _used_ to work as advertised. In the intervening time, however, Portage added a [new `${L10N}` environment variable](https://wiki.gentoo.org/wiki/Localization/Guide) conflicting with the existing `${L10N}` environment variable leveraged for a completely different purpose by the Cataclysm: DDA `Makefile`. In short, bad stuff happened.

See #49 for further commentary, gratitude, and adulation.
