### ISSUE TITLE
media-sound/vgmplay doesn't compile when libao isn't installed

### ISSUE THREAD

**Issue by ValleyBell** [leycec/raiagent#62]
It's actually my fault that it does this.  
The Makefile enables libao by default unless you patch it. It also ignores the `opl` USE flag due to similar reasons.

You can use this patch to fix this
```diff
diff --git a/VGMPlay/Makefile b/VGMPlay/Makefile
index 520ab84..df78cd1 100644
--- a/VGMPlay/Makefile
+++ b/VGMPlay/Makefile
@@ -16,10 +16,10 @@
 #MACOSX = 1
 
 # disable Hardware OPL Support
-DISABLE_HWOPL_SUPPORT = 1
+#DISABLE_HWOPL_SUPPORT = 1
 
 # Uncomment if you want to use libao instead of OSS for sound streaming under Linux
-USE_LIBAO = 1
+#USE_LIBAO = 1
 
 # Uncomment for debug builds
 #DEBUG = 1
```
I'll fix this in the Git repo later. The patch will be required for all releases <= 0.40.8 though.

**Comment by leycec** [comment]
> It's actually my fault that it does this.

It's... it's *not* actually my fault? I have never heard those words before this fateful day.

> You can use this patch to fix this...

**Pure excellence.** Because maintaining diffs against a moving target (namely, your very superb `vgmplay` codebase) is hard *and* I am soft and lazy, I'll probably refactor these two changes into `sed`-based regex replacements.

This shall happen soon. Maybe when I drop the 0.40.8 bomb? <sup>*Tomorrow. Always tomorrow.*</sup>

> I'll fix this in the Git repo later. The patch will be required for all releases <= 0.40.8 though.

Understood. Thanks again for the detailed report. We'll right this sinking ship yet! 🚢

**Comment by leycec** [comment]
*Bam!* Everything appears to behave as expected for 0.48.0 now. 🍾
