### ISSUE TITLE
games-roguelike/cataclysm-dda: cataclysm-tiles falling back to ASCII

### ISSUE THREAD

**Issue by cmopper** [leycec/raiagent#69]
I installed **games-roguelike/cataclysm-dda** with the following USE flags: **lua ncurses nls sdl sound**. The game builds and installs fine. But when I run cataclysm-tiles, it uses ASCII graphics.

I verified in options that tiles are enabled. When I try to switch to another tileset and save options, the following message window is shown:

Loading the tileset failed: Could not load tileset image at
/usr/share/cataclysm-dda///usr/share/cataclysm-dda/gfx/HoderTileset/hodertiles.png, error: Couldn't open /usr/share/cataclysm-dda///usr/share/cataclysm-dda/gfx/HoderTileset/hodertiles.png

The same message is also shown if I toggle "**Use tiles**" option and then save config.

I see that ebuild changes some hardcoded paths for data files since portage builds packages in a sandbox. I suspect there might be some problem in the way ebuild changes hardcodes.

**Comment by cmopper** [comment]
I have to correct myself. Some tilesets are working:

- ChestHole
- RetroDays20px
- RetroDays10px
- RetroASCII
- MShock32
- MShock24

Tilesets that produce above error when switching to them:

- Hoder's
- Deon's
- Blockhead's
- Tsu's
- Thuztor'@

**Comment by leycec** [comment]
Wow! You're awesome. Thanks for the super-hyper-detailed writeup. It's fascinating that only a proper subset of the tilesets now behave as expected. As you intuit, this is almost certainly the fault of our ebuild failing to install tileset assets to sane installation directories.

It's been a... trying month. (Read: *it's been Doom 2-style Hell on Earth.*) Nonetheless, I'll endeavour to resolve this as soon as feasible – hopefully this weekend, assuming the Arachnotron that is real life responsibilities gives me some breathing space. `</urgh!>`

**Comment by leycec** [comment]
**Boom!** :boom: 

#7834f3 both resolves this issue *and* bumps the stable release to the recently released and long-anticipated **0.D (Denny).** Due to a growing number of instabilities in the `experimental` branch of the live C:DDA repository, users are *strongly* advised to switch from the unstable `9999` release to the stable `0.D` release. Notably, `/etc/portage/package.accept_keywords` should contain a fragment resembling:

```
>=games-roguelike/cataclysm-dda-0.9d
#>=games-roguelike/cataclysm-dda-0.9d **
```

Thanks both for the detailed writeup and your commendable patience, @cmopper. Although I've tested this exhaustively, I'd be grateful if you could test this a bit on your end as well. If one or more tilesets remain inaccessible for you, please reopen this issue.

This distressing necro-neckbeard is for you! :neckbeard:
