### ISSUE TITLE
shiboken2*.pc files have broken Cflags and probably Libs

### ISSUE THREAD

**Issue by soltysek** [leycec/raiagent#75]
Hi it is me again :stuck_out_tongue:

Thanks for fixing previous issues with pc files but I looks like there is another problem.
All shiboken2*.pc files have Libs and Cflags defined this way:
```
Libs:  -L${libdir} -lshiboken2-<python version>-<python version>
Cflags: -I/usr/include/<python version> -I${includedir}/-<python version>
```
Cflags during compilation looks like:
```  
Cflags: -I/usr/include/<python version> -I/usr/include/shiboken2/-<python version>
```
Directory /usr/include/shiboken2/**-\<python version\>** does not exist o compiler is failing to locate proper header files. This should be fixed, as all header files for shiboken2 are in **/usr/include/shiboken2**. Probably similar problem will exists also for Llibs.

It would be great if you can fix this :smiley:

**Comment by leycec** [comment]
**Ugh.** Yup, that's blatantly broken. I should've noticed that myself. In my humble defense, the Shiboken2 `CMakeLists.txt` file generating these `pkgconfig` files itself appears to be blatantly broken – which is why we keep stumbling over impassible roadblocks like this. Upstream bugs become our bugs. I shake my fist in a futile manner at The Qt Company!

I'll patch this up for everybody over the next several days. While I'm at it, I'll *also* inspect the `pkgconfig` files for PySide2 and patch those if needed as well. This should be the last either of us ever hear of these sorts of issues. <sup>*...grrrrrrrrrrrrrrrr*</sup>

**Comment by leycec** [comment]
**Yay!** Cost-efficient tech support strikes again. Like any poorly paid call centre desk jockey viciously chained to his cubicle partition, I cannot guarantee success.

I guarantee only anger, misery, and salty tears. Behold: possibly working Shiboken2 and PySide2 ebuilds on Gentoo! <sup>part deux</sup>
