### ISSUE TITLE
zeronet: PYTHON_USEDEP-HAS-BEEN-REMOVED

### ISSUE THREAD

**Issue by kcgthb** [leycec/raiagent#81]
Hi!

It looks like some ebuilds may need an update after https://archives.gentoo.org/gentoo-dev/message/87d351258522c1bd8b2f3052d4a4e2bd ?

``` 
- net-vpn/zeronet-0.6.2::raiagent (masked by: invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 6 in '/var/db/pkg/net-vpn/zeronet-0.6.2/RDEPEND')
```
```
# emerge -av zeronet

These are the packages that would be merged, in order:

Calculating dependencies... done!

!!! All ebuilds that could satisfy "zeronet" have been masked.
!!! One of the following masked packages is required to complete your request:
- net-vpn/zeronet-9999-r2::raiagent (masked by: missing keyword, invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 21)
- net-vpn/zeronet-0.7.1-r1::raiagent (masked by: ~amd64 keyword, invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 21)
- net-vpn/zeronet-0.6.5::raiagent (masked by: ~amd64 keyword, invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 6)
- net-vpn/zeronet-0.6.4-r1::raiagent (masked by: ~amd64 keyword, invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 6)
- net-vpn/zeronet-0.6.2::raiagent (masked by: invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 6)
- net-vpn/zeronet-0.6.0::raiagent (masked by: ~amd64 keyword, invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 6)

For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

**Comment by leycec** [comment]
Your link tragically resolves to an unrelated OpenSSH issue, but... **yikes!** Removing `${PYTHON_USEDEP}` from `python-single-r1.eclass` fundamentally breaks existing Python ebuilds and Python-centric overlays – including this one.

Portage maintainters *really* should've added this breaking change to a bumped `python-single-r2.eclass` rather than breaking backward with the entire Python ebuild ecosystem. Alternately, they could have simply preserved `${PYTHON_USEDEP}` as a deprecated alias to `${PYTHON_SINGLE_USEDEP}`. Of course, they opted instead to break everything. *So much incoherent rage.* :rage4: 

Given the extent of the damage, this'll probably take a few days to knit back together. Thanks for the heads up, @kcgthb. Unlike Portage maintainers, you are a hero among mere mortals. Vowels are, indeed, overrated. **Let's do this!**

**Comment by kcgthb** [comment]
Dang, sorry for the mixed up link. I meant this: https://archives.gentoo.org/gentoo-dev/message/c381a2db549d2e3aa12fef6955b47ebe

And thank you!!

**Comment by leycec** [comment]
**Bam!** This breakage annoys the Canadian Beaver Scout inside of all of us, so... *it is done.* Relatedly, I've also added [GLEP 081 support](https://www.gentoo.org/glep/glep-0081.html) to ZeroNet ebuilds – which means that you'll now need to be a bit more specific when instructing Portage to do ZeroNet-related things (e.g., `emerge net-vpn/zeronet` rather than merely `emerge zeronet`, which is now sadly ambiguous).

Thanks a [Canadian toonie](https://en.wikipedia.org/wiki/Toonie) for the intrepid bug report, @kcgthb! :medal_sports:

**Comment by kcgthb** [comment]
Thank _you_ for the quick fix!
