### ISSUE TITLE
dev-python/pyside2-5.14.1-r2::raiagent compile failed

### ISSUE THREAD

**Issue by kittkott** [leycec/raiagent#85]
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/cstddef:50:10: fatal: 'stddef.h' file not found

```
find /usr/lib/gcc/x86_64-pc-linux-gnu/ | grep stdlib.h
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/stdlib.h
/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/tr1/stdlib.h
```
sys-devel/gcc-8.3.0-r3 (cxx fortran go multilib nls nptl objc objc++ objc-gc openmp pch pie sanitize ssp vtv -ada -altivec -debug -doc -fixed-point -graphite -hardened -jit -libssp -mpx -pgo -systemtap -test -vanilla)

Portage 2.3.99 (python 3.6.10-final-0, default/linux/amd64/17.1/desktop/plasma, gcc-8.3.0, glibc-2.30-r8, 5.6.4-gentoo x86_64)
System uname: Linux-5.6.4-gentoo-x86_64-Intel-R-_Core-TM-_i5-8250U_CPU_@_1.60GHz-with-gentoo-2.7
sh bash 5.0_p16
ld GNU ld (Gentoo 2.33.1 p2) 2.33.1
app-shells/bash:          5.0_p16::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.2::gentoo
dev-lang/python:          2.7.17-r2::gentoo, 3.6.10::gentoo
dev-util/cmake:           3.17.1::gentoo
sys-apps/baselayout:      2.7::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.18::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
sys-devel/automake:       1.13.4-r2::gentoo, 1.16.2::gentoo
sys-devel/binutils:       2.33.1-r1::gentoo
sys-devel/gcc:            8.3.0-r3::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.6::gentoo (virtual/os-headers)
sys-libs/glibc:           2.30-r8::gentoo
Repositories:

CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -O2 -pipe -fomit-frame-pointer -mfpmath=sse -funroll-loops -g0"
CHOST="x86_64-pc-linux-gnu"

FCFLAGS="-O2 -pipe"
FFLAGS="-O2 -pipe"
LANG="ru_RU.UTF-8"
LDFLAGS="-Wl,--as-needed"
LINGUAS="ru en ru_RU en_US"
MAKEOPTS="-j4"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" 
ELIBC="glibc" 
PYTHON_SINGLE_TARGET="python3_6" 
PYTHON_TARGETS="python3_6"

[/var/tmp/portage/dev-python/pyside2-5.14.1-r2/temp/build.log](https://pastebin.com/A1TLYgMS)

**Comment by leycec** [comment]
**Apologies for the extreme delay.** I completely missed this until now. Of course, pastebin has since removed your build log. :facepalm: 

Since `'stddef.h' file not found` errors have been increasingly common lately, I'll probably bump the PySide2 family of ebuilds to Qt 5.14.2. With any luck, that will solve everything for everyone and I can return to my idyllic man-cave filled with questionable video games and copious free time.

**Comment by leycec** [comment]
**Success!** Or rather abject failure, but I'll take what I can get. I just hit this exact `'stddef.h' file not found` issue after bumping our PySide2 and shiboken2 ebuilds to Qt 5.14.2 – which means I can now actually debug and resolve this for the good of all Gentookind. `</phew>`

Let's do this, Team Raiagent™!

**Comment by leycec** [comment]
**Fascinating.** It would seem that CLang builtin includes no longer reside in `/usr/lib/clang/${CLANG_VERSION}/include/` but rather in `/usr/lib/gcc/${ARCH}/${GCC_VERSION}/include/`. In theory, this means that all we need to do now is change our `src_prepare()` patch to reference the latter rather than former directory.

That said, this is all a bit too fragile. This should just *work* out of the box. It doesn't. Why? Nobody knows – including me. Let's do a bit more grepping and see if we can find a more dependable resolution. `</sigh>`

**Comment by leycec** [comment]
**Wowza!** This sure was a nightmarish issue – and still is. The underlying issue (on my system, anyways) is that the PySide2 build system improperly detects the currently installed Clang version. For unknown reasons, my system contains a totally b0rked `/usr/lib/clang/10.0.0/include/` subdirectory that does *not* contain anything useful:

```
$ ls /usr/lib/clang/10.0.0/include/
.  ..  fuzzer  sanitizer  xray
```

Yikes. For comparison, here's a totally w0rky `/usr/lib/clang/9.0.1/include/` subdirectory that contains everything useful:

```
$ ls /usr/lib/clang/9.0.1/include/
.                       avx512vldqintrin.h                    gfniintrin.h      smmintrin.h
..                      avx512vlintrin.h                      htmintrin.h       stdalign.h
cuda_wrappers           avx512vlvbmi2intrin.h                 htmxlintrin.h     stdarg.h
openmp_wrappers         avx512vlvnniintrin.h                  ia32intrin.h      stdatomic.h
ppc_wrappers            avx512vlvp2intersectintrin.h          immintrin.h       stdbool.h
sanitizer               avx512vnniintrin.h                    intrin.h          stddef.h
xray                    avx512vp2intersectintrin.h            inttypes.h        __stddef_max_align_t.h
adxintrin.h             avx512vpopcntdqintrin.h               invpcidintrin.h   stdint.h
altivec.h               avx512vpopcntdqvlintrin.h             iso646.h          stdnoreturn.h
ammintrin.h             avxintrin.h                           limits.h          tbmintrin.h
arm64intr.h             bmi2intrin.h                          lwpintrin.h       tgmath.h
arm_acle.h              bmiintrin.h                           lzcntintrin.h     tmmintrin.h
arm_fp16.h              cetintrin.h                           mm3dnow.h         unwind.h
armintr.h               __clang_cuda_builtin_vars.h           mmintrin.h        vadefs.h
arm_neon.h              __clang_cuda_cmath.h                  mm_malloc.h       vaesintrin.h
avx2intrin.h            __clang_cuda_complex_builtins.h       module.modulemap  varargs.h
avx512bf16intrin.h      __clang_cuda_device_functions.h       movdirintrin.h    vecintrin.h
avx512bitalgintrin.h    __clang_cuda_intrinsics.h             msa.h             vpclmulqdqintrin.h
avx512bwintrin.h        __clang_cuda_libdevice_declares.h     mwaitxintrin.h    waitpkgintrin.h
avx512cdintrin.h        __clang_cuda_math_forward_declares.h  nmmintrin.h       wbnoinvdintrin.h
avx512dqintrin.h        __clang_cuda_runtime_wrapper.h        opencl-c-base.h   __wmmintrin_aes.h
avx512erintrin.h        cldemoteintrin.h                      opencl-c.h        wmmintrin.h
avx512fintrin.h         clflushoptintrin.h                    pconfigintrin.h   __wmmintrin_pclmul.h
avx512ifmaintrin.h      clwbintrin.h                          pkuintrin.h       x86intrin.h
avx512ifmavlintrin.h    clzerointrin.h                        pmmintrin.h       xmmintrin.h
avx512pfintrin.h        cpuid.h                               popcntintrin.h    xopintrin.h
avx512vbmi2intrin.h     emmintrin.h                           prfchwintrin.h    xsavecintrin.h
avx512vbmiintrin.h      enqcmdintrin.h                        ptwriteintrin.h   xsaveintrin.h
avx512vbmivlintrin.h    f16cintrin.h                          rdseedintrin.h    xsaveoptintrin.h
avx512vlbf16intrin.h    float.h                               rtmintrin.h       xsavesintrin.h
avx512vlbitalgintrin.h  fma4intrin.h                          s390intrin.h      xtestintrin.h
avx512vlbwintrin.h      fmaintrin.h                           sgxintrin.h
avx512vlcdintrin.h      fxsrintrin.h                          shaintrin.h
```

So, there are two intersecting issues here:

1. Some Gentoo systems (like mine and probably yours) contain broken Clang installs.
1. The functionally braindead PySide2 build system erroneously...
    * ...uses the `/usr/lib/clang/${CLANG_BIGGEST_VERSION}/include/` subdirectory, where `${CLANG_BIGGEST_VERSION}` is the largest version specifier that exists (e.g., `10.0.0`), even if that subdirectory is totally b0rked.
   * ...rather than the `/usr/lib/clang/${CLANG_ACTUAL_VERSION}/include/` subdirectory, where `${CLANG_ACTUAL_VERSION}` is the currently installed version of Clang.

We obviously can't fix 1., so we need to fix 2. instead. To do so, we'll need to completely circumvent the functionally braindead `findClangBuiltInIncludesDir()` function in the `sources/shiboken2/ApiExtractor/clangparser/compilersupport.cpp` with some clever `sed` patching.

Curses upon ye, The Qt Company! Curses! :raccoon:

**Comment by leycec** [comment]
**Done** and **done.** This was an *absolutely* insane issue to resolve, thanks to inadequacies in PySide2's non-standard build system as well as [an unresolved issue in the `toolfunc-chains` eclass that made this much more hellish than it had to be](https://bugs.gentoo.org/619490#c4).

Honestly, there just needs to be an eclass function that gets the current Clang includes directory. There isn't. Much mental anguish and debilitating anger follows. Rage, rage at the dying of the ebuild light, DOOM guy! :rage1: :rage2: :rage3: :rage4:

**Comment by kittkott** [comment]
All bug fixed
[ebuild     U ] dev-python/shiboken2-5.14.2 [5.14.1-r2] USE="docstrings vulkan -numpy -test" PYTHON_TARGETS="python3_7 -python3_6 -python3_8 (-python2_7%)"
[ebuild  N    ] dev-python/pyside2-5.14.2  USE="gui svg widgets -3d -charts -concurrent -datavis -designer -gles2-only -help -location -multimedia-network -positioning -printsupport -qml -quick -script -scripttools -scxml -sensors -speech -sql -test -testlib -webchannel -webengine -websockets -x11extras -xml -xmlpatterns" PYTHON_TARGETS="python3_7 -python3_6 -python3_8"

>>> Emerging (1 of 2) dev-python/shiboken2-5.14.2::raiagent
>>> Installing (1 of 2) dev-python/shiboken2-5.14.2::raiagent
>>> Emerging (2 of 2) dev-python/pyside2-5.14.2::raiagent
>>> Installing (2 of 2) dev-python/pyside2-5.14.2::raiagent
>>> Recording dev-python/pyside2 in "world" favorites file...
>>> Jobs: 2 of 2 complete
