### ISSUE TITLE
moved a few things to gentoo

### ISSUE THREAD

**Issue by ZeroChaos-** [leycec/raiagent#89]
hey.  as I mentioned earlier I needed shiboken2 and pyside2, and preferring "works" to "perfect" I've added shiboken2 and pyside2 to gentoo.  Despite the test failures, it does seem to work, and that's what I need, I need it to work :-)

Thanks for your hard work.

You can maintain this in your overlay if you want, or just poke me with fixes to push into gentoo.  You can find me on irc and a bunch of different discords.  Also a PR against gentoo where I'm mentioned will probably get my attention.  Thanks again, this ebuild looks like it was a lot of work and I'm super happy to have it when I needed it.  I've been wanting pyside2 for a while but when I tried long ago I gave up pretty quick :-)

**Comment by leycec** [comment]
**Phenomenal work!** Relatedly, did you happen to [get my final comment at #88](https://github.com/leycec/raiagent/issues/88#issuecomment-632510672)? The PySide2 5.14.2 ebuild in Portage is sadly lacking significant improvements that I committed above seven hours before you submitted this issue – notably, my prior two commits (a6801ab  and 9b6b993) effectively resolved #88 and a host of other related OpenGL and Vulkan issues by:

* Adding `dev-qt/qtcore` as an unconditional RDEPEND to `dev-python/pyside2`.
* Unconditionally disabling the deprecated `PySide2.QtOpenGL` submodule, thus preventing `dev-python/pyside2` from implicitly RDEPENDing on the deprecated `dev-qt/qtopengl` package.
* Properly supporting the existing `gles2-only` USE flag. Namely:
  * Disabling this flag now explicitly disables GLES2 support in both the `PySide2.QtGui` and `PySide2.OpenGLFuncctions` submodules.
  * This flag is now propagated to all Qt dependencies.
* Adding a new `vulkan` USE flag, propagating Vulkan support to both shiboken2 and Qt dependencies.

I assume Portage users might like those things, too – but, hey! I ain't complainin'. I'm *extraordinarily* relieved to have the burden of maintaining PySide2 ebuilds lifted from my emaciated shoulders and onto the Gentoo community as a whole.

Going forward, I'll probably:

* Preserve the existing PySide2 and shiboken2 ebuilds at this overlay for a few weeks (modified to log a deprecation warning that users should strongly prefer official Portage ebuilds) before permanentely removing them.
* Preserve the existing `pyside2-tools` ebuild, which appears to have no official Portage counterpart at the moment. That's fine, of course. That package is trivial to maintain and I'm happy to continue doing it. If you or another dev *do* get around to adding `pyside2-tools` to Portage, though, would you mind pinging me when that happens?

> You can find me on irc...

`#gentoo` it is! A nicer bunch of geek malcontents man will never find.

> ...this ebuild looks like it was a lot of work...

*We don't talk about that.*

O.K., very well. These ebuilds were cray-cray – definitely the second-most excruciating packages to maintain. Because *nothing* is more excruciating than [packaging ZeroNet](https://github.com/HelloZeroNet/ZeroNet/issues/382#issuecomment-304420648).

> ...and I'm super happy to have it when I needed it.

Delighted to be of service. Out of curiosity, which PySide2 reverse dependency was it that you needed? FreeCAD? Maya? Pixar's `usdview`? Something else entirely? 

> I've been wanting pyside2 for a while but when I tried long ago I gave up pretty quick :-)

This sounds like me in a happier parallel universe. In this universe, I just didn't know when to quit.

I can't thank you enough. You've made my all-too-brief Canadian summer weekend, @ZeroChaos-! Drop me a line here or anywhere if you need anything whatsoever.

I'll briefly leave this open until I get around to deprecating the PySide2 and shiboken2 ebuilds hosted here. :clap: :handshake: :champagne:

**Comment by leycec** [comment]
It's been *ages*, so let's close this out. Thanks, @ZeroChaos-! Our work here is done.
